-- SQL Script to add 50 products and 50 suppliers to the database

-- Select the database
USE axalta;

-- Products
INSERT IGNORE INTO products (name, description, unit, category, base_price) VALUES
('Acrylic Paint - White', 'High-quality acrylic paint, white color', 'gallon', 'Paint', 45.99),
('Acrylic Paint - Black', 'High-quality acrylic paint, black color', 'gallon', 'Paint', 45.99),
('Acrylic Paint - Red', 'High-quality acrylic paint, red color', 'gallon', 'Paint', 48.99),
('Acrylic Paint - Blue', 'High-quality acrylic paint, blue color', 'gallon', 'Paint', 48.99),
('Acrylic Paint - Green', 'High-quality acrylic paint, green color', 'gallon', 'Paint', 48.99),
('Acrylic Paint - Yellow', 'High-quality acrylic paint, yellow color', 'gallon', 'Paint', 48.99),
('Acrylic Paint - Orange', 'High-quality acrylic paint, orange color', 'gallon', 'Paint', 48.99),
('Acrylic Paint - Purple', 'High-quality acrylic paint, purple color', 'gallon', 'Paint', 48.99),
('Acrylic Paint - Brown', 'High-quality acrylic paint, brown color', 'gallon', 'Paint', 48.99),
('Acrylic Paint - Gray', 'High-quality acrylic paint, gray color', 'gallon', 'Paint', 48.99),
('Oil Paint - White', 'Premium oil-based paint, white color', 'gallon', 'Paint', 55.99),
('Oil Paint - Black', 'Premium oil-based paint, black color', 'gallon', 'Paint', 55.99),
('Oil Paint - Red', 'Premium oil-based paint, red color', 'gallon', 'Paint', 58.99),
('Oil Paint - Blue', 'Premium oil-based paint, blue color', 'gallon', 'Paint', 58.99),
('Oil Paint - Green', 'Premium oil-based paint, green color', 'gallon', 'Paint', 58.99),
('Primer - White', 'All-purpose primer, white', 'gallon', 'Primer', 39.99),
('Primer - Gray', 'All-purpose primer, gray', 'gallon', 'Primer', 39.99),
('Epoxy Resin', 'High-strength epoxy resin', 'liter', 'Resin', 65.99),
('Polyurethane Resin', 'Flexible polyurethane resin', 'liter', 'Resin', 72.99),
('Acrylic Resin', 'Clear acrylic resin', 'liter', 'Resin', 59.99),
('Polyester Resin', 'Durable polyester resin', 'liter', 'Resin', 68.99),
('Vinyl Resin', 'Industrial vinyl resin', 'liter', 'Resin', 64.99),
('Alkyd Resin', 'Fast-drying alkyd resin', 'liter', 'Resin', 67.99),
('Phenolic Resin', 'Heat-resistant phenolic resin', 'liter', 'Resin', 71.99),
('Melamine Resin', 'Durable melamine resin', 'liter', 'Resin', 69.99),
('Titanium Dioxide', 'Pure titanium dioxide pigment', 'kg', 'Pigment', 42.99),
('Carbon Black', 'High-grade carbon black pigment', 'kg', 'Pigment', 38.99),
('Iron Oxide Red', 'Natural iron oxide red pigment', 'kg', 'Pigment', 36.99),
('Ultramarine Blue', 'Vibrant ultramarine blue pigment', 'kg', 'Pigment', 45.99),
('Chromium Oxide Green', 'Stable chromium oxide green pigment', 'kg', 'Pigment', 47.99),
('Xylene', 'Industrial-grade xylene solvent', 'liter', 'Solvent', 32.99),
('Toluene', 'Pure toluene solvent', 'liter', 'Solvent', 34.99),
('Acetone', 'High-purity acetone solvent', 'liter', 'Solvent', 29.99),
('Methyl Ethyl Ketone', 'MEK solvent', 'liter', 'Solvent', 36.99),
('Isopropyl Alcohol', '99% isopropyl alcohol', 'liter', 'Solvent', 27.99),
('Polyurethane Varnish - Gloss', 'Durable polyurethane varnish, gloss finish', 'liter', 'Varnish', 49.99),
('Polyurethane Varnish - Satin', 'Durable polyurethane varnish, satin finish', 'liter', 'Varnish', 49.99),
('Polyurethane Varnish - Matte', 'Durable polyurethane varnish, matte finish', 'liter', 'Varnish', 49.99),
('Acrylic Varnish - Gloss', 'Water-based acrylic varnish, gloss finish', 'liter', 'Varnish', 44.99),
('Acrylic Varnish - Satin', 'Water-based acrylic varnish, satin finish', 'liter', 'Varnish', 44.99),
('Acrylic Varnish - Matte', 'Water-based acrylic varnish, matte finish', 'liter', 'Varnish', 44.99),
('Epoxy Floor Coating - Gray', 'Industrial epoxy floor coating, gray', 'gallon', 'Floor Coating', 89.99),
('Epoxy Floor Coating - Beige', 'Industrial epoxy floor coating, beige', 'gallon', 'Floor Coating', 89.99),
('Epoxy Floor Coating - Blue', 'Industrial epoxy floor coating, blue', 'gallon', 'Floor Coating', 92.99),
('Epoxy Floor Coating - Green', 'Industrial epoxy floor coating, green', 'gallon', 'Floor Coating', 92.99),
('Epoxy Floor Coating - Red', 'Industrial epoxy floor coating, red', 'gallon', 'Floor Coating', 92.99),
('Polyurethane Floor Coating - Clear', 'Durable polyurethane floor coating, clear', 'gallon', 'Floor Coating', 94.99),
('Polyurethane Floor Coating - Amber', 'Durable polyurethane floor coating, amber tint', 'gallon', 'Floor Coating', 94.99),
('Anti-Corrosion Primer', 'Industrial anti-corrosion primer', 'gallon', 'Primer', 62.99),
('High-Heat Resistant Paint', 'Paint resistant to temperatures up to 1200°F', 'gallon', 'Paint', 78.99);

-- Suppliers
INSERT IGNORE INTO suppliers (name, email, phone, address, city, state, country, postal_code, status) VALUES
('Global Paint Supply Co.', 'contact@globalpaintsupply.com', '555-123-4567', '123 Main St', 'Chicago', 'IL', 'USA', '60601', 'ACTIVE'),
('Premier Chemical Industries', 'sales@premierchemical.com', '555-234-5678', '456 Oak Ave', 'Houston', 'TX', 'USA', '77001', 'ACTIVE'),
('Acme Coating Solutions', 'info@acmecoating.com', '555-345-6789', '789 Pine Rd', 'Los Angeles', 'CA', 'USA', '90001', 'ACTIVE'),
('Industrial Pigments Ltd.', 'orders@industrialpigments.com', '555-456-7890', '101 Elm Blvd', 'New York', 'NY', 'USA', '10001', 'ACTIVE'),
('Resin Technologies Inc.', 'support@resintechnologies.com', '555-567-8901', '202 Maple Dr', 'Seattle', 'WA', 'USA', '98101', 'ACTIVE'),
('Solvent Solutions LLC', 'info@solventsolutions.com', '555-678-9012', '303 Cedar Ln', 'Denver', 'CO', 'USA', '80201', 'ACTIVE'),
('Quality Chemicals Corp.', 'sales@qualitychemicals.com', '555-789-0123', '404 Birch St', 'Atlanta', 'GA', 'USA', '30301', 'ACTIVE'),
('Advanced Coatings Group', 'contact@advancedcoatings.com', '555-890-1234', '505 Walnut Ave', 'Boston', 'MA', 'USA', '02101', 'ACTIVE'),
('Pigment Professionals', 'orders@pigmentpro.com', '555-901-2345', '606 Spruce Rd', 'Philadelphia', 'PA', 'USA', '19101', 'ACTIVE'),
('EcoSolve Chemicals', 'info@ecosolve.com', '555-012-3456', '707 Fir Blvd', 'San Francisco', 'CA', 'USA', '94101', 'ACTIVE'),
('Polymer Products Inc.', 'sales@polymerproducts.com', '555-123-4568', '808 Ash Dr', 'Phoenix', 'AZ', 'USA', '85001', 'ACTIVE'),
('Color Science Labs', 'contact@colorscience.com', '555-234-5679', '909 Oak Ln', 'Miami', 'FL', 'USA', '33101', 'ACTIVE'),
('Industrial Solutions Group', 'info@industrialsolutions.com', '555-345-6780', '111 Pine St', 'Detroit', 'MI', 'USA', '48201', 'ACTIVE'),
('ChemSource International', 'orders@chemsource.com', '555-456-7891', '222 Elm Ave', 'Minneapolis', 'MN', 'USA', '55401', 'ACTIVE'),
('Coating Specialists Ltd.', 'support@coatingspecialists.com', '555-567-8902', '333 Maple Rd', 'Cleveland', 'OH', 'USA', '44101', 'ACTIVE'),
('Resin Research Corp.', 'info@resinresearch.com', '555-678-9013', '444 Cedar St', 'Portland', 'OR', 'USA', '97201', 'ACTIVE'),
('Paint Chemistry Inc.', 'sales@paintchemistry.com', '555-789-0124', '555 Birch Ave', 'Dallas', 'TX', 'USA', '75201', 'ACTIVE'),
('Solvent Systems LLC', 'contact@solventsystems.com', '555-890-1235', '666 Walnut Rd', 'San Diego', 'CA', 'USA', '92101', 'ACTIVE'),
('Pigment Plus Corp.', 'orders@pigmentplus.com', '555-901-2346', '777 Spruce St', 'Las Vegas', 'NV', 'USA', '89101', 'ACTIVE'),
('Chemical Innovations', 'info@chemicalinnovations.com', '555-012-3457', '888 Fir Ave', 'Nashville', 'TN', 'USA', '37201', 'ACTIVE'),
('Coating Technologies', 'sales@coatingtech.com', '555-123-4569', '999 Ash Rd', 'Charlotte', 'NC', 'USA', '28201', 'ACTIVE'),
('Resin Supply Co.', 'contact@resinsupply.com', '555-234-5670', '123 Oak St', 'Indianapolis', 'IN', 'USA', '46201', 'ACTIVE'),
('Advanced Pigments Inc.', 'info@advancedpigments.com', '555-345-6781', '456 Pine Ave', 'Columbus', 'OH', 'USA', '43201', 'ACTIVE'),
('Solvent Experts LLC', 'orders@solventexperts.com', '555-456-7892', '789 Elm Rd', 'Kansas City', 'MO', 'USA', '64101', 'ACTIVE'),
('Premier Paint Products', 'support@premierpaint.com', '555-567-8903', '101 Maple St', 'St. Louis', 'MO', 'USA', '63101', 'ACTIVE'),
('Chemical Supply Group', 'info@chemicalsupply.com', '555-678-9014', '202 Cedar Ave', 'Pittsburgh', 'PA', 'USA', '15201', 'ACTIVE'),
('Coating Resources Inc.', 'sales@coatingresources.com', '555-789-0125', '303 Birch Rd', 'Cincinnati', 'OH', 'USA', '45201', 'ACTIVE'),
('Pigment Technologies', 'contact@pigmenttechnologies.com', '555-890-1236', '404 Walnut St', 'Milwaukee', 'WI', 'USA', '53201', 'ACTIVE'),
('Solvent Solutions Plus', 'info@solventsolutionsplus.com', '555-901-2347', '505 Spruce Ave', 'Salt Lake City', 'UT', 'USA', '84101', 'ACTIVE'),
('Resin World LLC', 'orders@resinworld.com', '555-012-3458', '606 Fir Rd', 'Oklahoma City', 'OK', 'USA', '73101', 'ACTIVE'),
('Paint Supply Depot', 'support@paintsupplydepot.com', '555-123-4570', '707 Ash St', 'New Orleans', 'LA', 'USA', '70112', 'ACTIVE'),
('Chemical Distributors Inc.', 'info@chemicaldistributors.com', '555-234-5671', '808 Oak Ave', 'Louisville', 'KY', 'USA', '40201', 'ACTIVE'),
('Coating Innovations LLC', 'sales@coatinginnovations.com', '555-345-6782', '909 Pine Rd', 'Buffalo', 'NY', 'USA', '14201', 'ACTIVE'),
('Pigment Supply Co.', 'contact@pigmentsupply.com', '555-456-7893', '111 Elm St', 'Richmond', 'VA', 'USA', '23219', 'ACTIVE'),
('Solvent Direct Inc.', 'info@solventdirect.com', '555-567-8904', '222 Maple Ave', 'Baltimore', 'MD', 'USA', '21201', 'ACTIVE'),
('Resin Solutions Group', 'orders@resinsolutions.com', '555-678-9015', '333 Cedar Rd', 'Albuquerque', 'NM', 'USA', '87101', 'ACTIVE'),
('Paint Chemistry Labs', 'support@paintchemistrylabs.com', '555-789-0126', '444 Birch St', 'Tucson', 'AZ', 'USA', '85701', 'ACTIVE'),
('Chemical Resources LLC', 'info@chemicalresources.com', '555-890-1237', '555 Walnut Ave', 'Omaha', 'NE', 'USA', '68101', 'ACTIVE'),
('Coating Supply Inc.', 'sales@coatingsupply.com', '555-901-2348', '666 Spruce Rd', 'Tulsa', 'OK', 'USA', '74103', 'ACTIVE'),
('Pigment Masters Corp.', 'contact@pigmentmasters.com', '555-012-3459', '777 Fir St', 'Memphis', 'TN', 'USA', '38103', 'ACTIVE'),
('Solvent Specialists', 'info@solventspecialists.com', '555-123-4571', '888 Ash Ave', 'Birmingham', 'AL', 'USA', '35203', 'ACTIVE'),
('Resin Experts Inc.', 'orders@resinexperts.com', '555-234-5672', '999 Oak Rd', 'Jacksonville', 'FL', 'USA', '32202', 'ACTIVE'),
('Paint Solutions Group', 'support@paintsolutions.com', '555-345-6783', '123 Pine St', 'Providence', 'RI', 'USA', '02903', 'ACTIVE'),
('Chemical Technologies', 'info@chemicaltechnologies.com', '555-456-7894', '456 Elm Ave', 'Hartford', 'CT', 'USA', '06103', 'ACTIVE'),
('Coating Professionals LLC', 'sales@coatingprofessionals.com', '555-567-8905', '789 Maple Rd', 'Manchester', 'NH', 'USA', '03101', 'ACTIVE'),
('Pigment Solutions Inc.', 'contact@pigmentsolutions.com', '555-678-9016', '101 Cedar St', 'Portland', 'ME', 'USA', '04101', 'ACTIVE'),
('Solvent Supply Co.', 'info@solventsupply.com', '555-789-0127', '202 Birch Ave', 'Boise', 'ID', 'USA', '83702', 'ACTIVE'),
('Resin Direct LLC', 'orders@resindirect.com', '555-890-1238', '303 Walnut Rd', 'Cheyenne', 'WY', 'USA', '82001', 'ACTIVE'),
('Paint Innovations Corp.', 'support@paintinnovations.com', '555-901-2349', '404 Spruce St', 'Billings', 'MT', 'USA', '59101', 'ACTIVE');
